services:
  seq:
    image: datalust/seq
    ports:
      - "5341:5341"
      - "5342:80"
    volumes:
      - seq_data:/data
    environment:
      - ACCEPT_EULA=Y
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=mquser
      - RABBITMQ_DEFAULT_PASS=verysecret
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  featurehub:
    image: featurehub/party-server:1.6.3
    ports:
      - "8085:8085"
    volumes:
      - featurehub_data:/db
  pongservice:
    build:
      dockerfile: Ponger/Dockerfile
  pingservice:
    build:
      dockerfile: Pinger/Dockerfile
    
volumes:
  seq_data:
  rabbitmq_data:
  featurehub_data: